[tool.poetry]
name = "capitalismbeta"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.7.3"
pymongo = "^3.11.4"
discord-py-slash-command = "^2.2.0"
python-dotenv = "^0.18.0"
jishaku = "^2.0.0"
image = "^1.5.33"
qrcode = "^7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
